DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(50) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS DOMICILIOS; CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(50) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(50) NOT NULL, PROVINCIA VARCHAR(50) NOT NULL);

DROP TABLE IF EXISTS PACIENTES; CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL, DNI INT NOT NULL, FECHA_DE_INGRESO DATE NOT NULL, ID_DOMICILIO INT NOT NULL);

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (584288,'LEIDY','ALZATE'),(654987,'LADY','SOTO'),(741852,'PABLO','ZAPATA');

INSERT INTO DOMICILIOS (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('LA RIOJA',1800,'CABA','BUENOS AIRES'), ('LA PLAYA',2548,'MEDELLIN','ANTIOQUIA');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA_DE_INGRESO, ID_DOMICILIO) VALUES ('ALEXANDRA','CARVAJAL',436545,'2023-06-28', 1), ('ALBERTO','DURANGO',852369,'2023-04-10', 2);
